// This file is generated by: flutterfire configure
// DO NOT edit manually.
//
// Run the following commands once to replace this file:
//   firebase login
//   flutterfire configure
//
// See SETUP.md for full instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Firebase is not configured yet.\n'
      'Run: firebase login\n'
      'Then: flutterfire configure\n'
      'See SETUP.md for details.',
    );
  }
}
